apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser-internal-ingress
  namespace: assetocorso-stack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    gethomepage.dev/description: filebrowser for assetocorso
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Assetocorso
    gethomepage.dev/name: filebrowser
    gethomepage.dev/ping: assetocorso-filebrowser.rke
    gethomepage.dev/pod-selector: ""
    nginx.ingress.kubernetes.io/proxy-buffers: "8"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/client-max-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
    - host: assetocorso-filebrowser.rke # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filebrowser-service
                port:
                  number: 8080
