apiVersion: apps/v1
kind: Deployment
metadata:
  name: assetto-corsa-server
  namespace: assetocorso-stack
spec:
  replicas: 0
  selector:
    matchLabels:
      app: assetto-corsa-server
  template:
    metadata:
      labels:
        app: assetto-corsa-server
        role: assetto-corsa-server
    spec:
      securityContext:
        fsGroup: 0
      containers:
        - name: assetto-corsa-server
          image: germanrcuriel/assetto-corsa-server
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York" # Replace with your timezone
            - name: STEAM_USER
              valueFrom:
                secretKeyRef:
                  name: assetto-corsa-steam-secret
                  key: STEAM_USER
            - name: STEAM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: assetto-corsa-steam-secret
                  key: STEAM_PASSWORD
            - name: AC_SERVER_NAME
              value: "Assetto Corsa Server"
            - name: AC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: assetto-corsa-server-secret
                  key: AC_PASSWORD
            - name: AC_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: assetto-corsa-server-secret
                  key: AC_ADMIN_PASSWORD
            - name: AC_HTTP_PORT
              value: "8081"
            - name: AC_TCP_PORT
              value: "9600"
            - name: AC_UDP_PORT
              value: "9600"
            - name: ST_USERNAME
              valueFrom:
                secretKeyRef:
                  name: assetto-corsa-stracker-secret
                  key: ST_USERNAME
            - name: ST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: assetto-corsa-stracker-secret
                  key: ST_PASSWORD
          ports:
            - name: ac-http
              containerPort: 8081
              protocol: TCP
            - name: ac-tcp
              containerPort: 9600
              protocol: TCP
            - name: ac-udp
              containerPort: 9600
              protocol: UDP
            - name: stracker
              containerPort: 50041
              protocol: TCP
            - name: ptracker
              containerPort: 50042
              protocol: TCP
          volumeMounts:
            - name: steamapps
              mountPath: /steamapps
      volumes:
        - name: steamapps
          persistentVolumeClaim:
            claimName: assetto-corsa-steamapps-pvc
