apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assetto-corsa-internal-ingress
  namespace: assetocorso-stack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    gethomepage.dev/description: Assetto Corsa Racing Server
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Assetto Corsa
    gethomepage.dev/name: AC Server
    gethomepage.dev/ping: assetto-corsa.rke
    gethomepage.dev/pod-selector: ""
spec:
  rules:
    - host: assetto-corsa.rke # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assetto-corsa-server-service
                port:
                  number: 8081

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stracker-internal-ingress
  namespace: assetocorso-stack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    gethomepage.dev/description: Stracker - AC Server Statistics
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Assetto Corsa
    gethomepage.dev/name: Stracker
    gethomepage.dev/ping: stracker.rke
    gethomepage.dev/pod-selector: ""
spec:
  rules:
    - host: stracker.rke # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assetto-corsa-server-service
                port:
                  number: 50041
