apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assetto-corsa-steamapps-pvc
  namespace: assetocorso-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # Assetto Corsa server needs space for game files
  storageClassName: longhorn # Explicitly set Longhorn as the storage class
