# apiVersion: v1
# kind: Service
# metadata:
#   name: radarr-service
#   namespace: media-stack
# spec:
#   selector:
#     app: radarr
#   ports:
#     - protocol: TCP
#       port: 7878
#       targetPort: 7878
#   type: ClusterIP
